export const PAGED_SEARCH_RESULT_ERRORS = {
  PAGE_MUST_BE_POSITIVE_NUMBER:
    "PAGED_SEARCH_RESULT.PAGE_MUST_BE_POSITIVE_NUMBER",
  SIZE_MUST_BE_POSITIVE_NUMBER:
    "PAGED_SEARCH_RESULT.SIZE_MUST_BE_POSITIVE_NUMBER",
  TOTAL_ELEMENTS_MUST_BE_POSITIVE_NUMBER:
    "PAGED_SEARCH_RESULT.TOTAL_ELEMENTS_MUST_BE_POSITIVE_NUMBER",
  TOTAL_PAGES_MUST_BE_POSITIVE_NUMBER:
    "PAGED_SEARCH_RESULT.TOTAL_PAGES_MUST_BE_POSITIVE_NUMBER",
};
