export const STOCK_HISTORY_ITEM_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "STOCK_HISTORY_ITEM.NOT_CONTAIN_NEEDED_PROPERTY",
  PREVIOUS_STOCK_MUST_BE_POSITIVE_NUMBER:
    "STOCK_HISTORY_ITEM.PREVIOUS_STOCK_MUST_BE_POSITIVE_NUMBER",
  NEW_STOCK_MUST_BE_POSITIVE_NUMBER:
    "STOCK_HISTORY_ITEM.NEW_STOCK_MUST_BE_POSITIVE_NUMBER",
  CHANGE_STOCK_MUST_BE_POSITIVE_NUMBER:
    "STOCK_HISTORY_ITEM.CHANGE_STOCK_MUST_BE_POSITIVE_NUMBER",
};
