export const INVENTORY_ITEM_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "INVENTORY_ITEM.NOT_CONTAIN_NEEDED_PROPERTY",
  SKU_INVALID_FORMAT: "INVENTORY_ITEM.SKU_INVALID_FORMAT",
  PRICE_MUST_BE_POSITIVE_NUMBER: "INVENTORY_ITEM.PRICE_MUST_BE_POSITIVE_NUMBER",
  QUANTITY_MUST_BE_POSITIVE_NUMBER:
    "INVENTORY_ITEM.QUANTITY_MUST_BE_POSITIVE_NUMBER",
};

export const INVENTORY_REPOSITORY_ERRORS = {
  METHOD_NOT_IMPLEMENTED: "INVENTORY_REPOSITORY.METHOD_NOT_IMPLEMENTED",
};
