export const ADD_PRODUCT_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "ADD_PRODUCT.NOT_CONTAIN_NEEDED_PROPERTY",
  SKU_INVALID_FORMAT: "ADD_PRODUCT.SKU_INVALID_FORMAT",
  PRODUCT_PRICE_MUST_BE_POSITIVE_NUMBER:
    "ADD_PRODUCT.PRODUCT_PRICE_MUST_BE_POSITIVE_NUMBER",
  PRODUCT_QUANTITY_MUST_BE_POSITIVE_NUMBER:
    "ADD_PRODUCT.PRODUCT_QUANTITY_MUST_BE_POSITIVE_NUMBER",
};

export const ADDED_PRODUCT_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "ADDED_PRODUCT.NOT_CONTAIN_NEEDED_PROPERTY",
  SKU_INVALID_FORMAT: "ADDED_PRODUCT.SKU_INVALID_FORMAT",
  PRODUCT_PRICE_MUST_BE_POSITIVE_NUMBER:
    "ADDED_PRODUCT.PRODUCT_PRICE_MUST_BE_POSITIVE_NUMBER",
  PRODUCT_QUANTITY_MUST_BE_POSITIVE_NUMBER:
    "ADDED_PRODUCT.PRODUCT_QUANTITY_MUST_BE_POSITIVE_NUMBER",
};

export const INVENTORY_REPOSITORY_ERRORS = {
  METHOD_NOT_IMPLEMENTED: "INVENTORY_REPOSITORY.METHOD_NOT_IMPLEMENTED",
};
