export const APPROVAL_REPOSITORY_ERRORS = {
  METHOD_NOT_IMPLEMENTED: "APPROVAL_REPOSITORY.METHOD_NOT_IMPLEMENTED",
};

export const ADD_PRODUCT_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "ADD_PRODUCT.NOT_CONTAIN_NEEDED_PROPERTY",
  SKU_INVALID_FORMAT: "ADD_PRODUCT.SKU_INVALID_FORMAT",
  PRICE_MUST_BE_POSITIVE_NUMBER: "ADD_PRODUCT.PRICE_MUST_BE_POSITIVE_NUMBER",
  QUANTITY_MUST_BE_POSITIVE_NUMBER:
    "ADD_PRODUCT.QUANTITY_MUST_BE_POSITIVE_NUMBER",
};

export const APPROVAL_REQUEST_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "APPROVAL_REQUEST.NOT_CONTAIN_NEEDED_PROPERTY",
};
