export const USER_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "USER.NOT_CONTAIN_NEEDED_PROPERTY",
  EMAIL_IS_INVALID: "USER.EMAIL_IS_INVALID",
  INDONESIAN_PHONE_NUMBER_IS_INVALID: "USER.INDONESIAN_PHONE_NUMBER_IS_INVALID",
  PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS:
    "USER.PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS",
  PASSWORD_MUST_CONTAIN_LETTERS_AND_NUMBERS:
    "USER.PASSWORD_MUST_CONTAIN_LETTERS_AND_NUMBERS",
  PASSWORD_MUST_NOT_CONTAIN_SPACE: "USER.PASSWORD_MUST_NOT_CONTAIN_SPACE",
} as const;

export const USER_REPOSITORY_ERRORS = {
  METHOD_NOT_IMPLEMENTED: "METHOD_NOT_IMPLEMENTED",
};
