export const METHOD_ASSERTION_ERRORS = {
  METHOD_NOT_IMPLEMENTED: "METHOD_ASSERTION.METHOD_NOT_IMPLEMENTED",
};

export const SECURE_STORAGE_ERRORS = {
  METHOD_NOT_IMPLEMENTED: "SECURE_STORAGE.METHOD_NOT_IMPLEMENTED",
};
