export const USER_LOGIN_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "USER_LOGIN.NOT_CONTAIN_NEEDED_PROPERTY",
  EMAIL_IS_INVALID: "USER_LOGIN.EMAIL_IS_INVALID",
  INDONESIAN_PHONE_NUMBER_IS_INVALID:
    "USER_LOGIN.INDONESIAN_PHONE_NUMBER_IS_INVALID",
  PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS:
    "USER_LOGIN.PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS",
  PASSWORD_MUST_CONTAIN_LETTERS_AND_NUMBERS:
    "USER_LOGIN.PASSWORD_MUST_CONTAIN_LETTERS_AND_NUMBERS",
  PASSWORD_MUST_NOT_CONTAIN_SPACE: "USER_LOGIN.PASSWORD_MUST_NOT_CONTAIN_SPACE",
} as const;

export const NEW_AUTH_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "USER_LOGIN.NOT_CONTAIN_NEEDED_PROPERTY",
} as const;

export const AUTH_REPOSITORY_ERRORS = {
  METHOD_NOT_IMPLEMENTED: "AUTH_REPOSITORY.METHOD_NOT_IMPLEMENTED",
} as const;

export const USER_LOGOUT_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "USER_LOGOUT.NOT_CONTAIN_NEEDED_PROPERTY",
};

export const REFRESH_TOKEN_ERRORS = {
  NOT_CONTAIN_NEEDED_PROPERTY: "USER_LOGOUT.NOT_CONTAIN_NEEDED_PROPERTY",
};
